# Generated by Django 3.2.8 on 2021-10-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='career',
            field=models.CharField(max_length=100),
        ),
    ]
